cart/urls.py
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [

    path('shoping_cart/', views.cart, name='shopping_cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('add_quantity_to_cart/<int:product_id>/<int:cart_item_id>/', views.add_quantity_to_cart, name='add_quantity_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    

    path('ajax/update/cart/', views.newcart_update, name='newcart_update'),
    path('ajax/remove/cart/', views.remove_cart_item_fully, name='remove_cart_item_fully'),


    path('add_from_wishlist/<int:product_id>',views.add_item_from_wishlist,name='add_from_wishlist')

   
]

category/urls.py
from django.urls import path,include
from . import views

app_name = 'category'

urlpatterns = [
    
    path('brand-list/', views.brand_list, name='brand-list'),
    path('add-brand/', views.add_brand, name='add_brand'),
    path('edit-brand/<str:brand_name>', views.edit_brand, name='edit_brand'),
    path('delete-brand/<str:brand_name>', views.delete_brand, name='delete_brand'),


    path('category-list/', views.category_list, name='category-list'),
    path('add-category/', views.add_category, name='add-category'),
    path('edit-category/<str:category_name>/', views.edit_category, name='edit-category'),
    path('delete-category/<str:category_name>/', views.delete_category, name='delete-category'),

    path('order_list/', views.order_list, name='order_list'),
    path('ordered_product_details/<int:order_id>', views.ordered_product_details, name='ordered_product_details'),
    path('update_order_status/<str:order_id>/', views.update_order_status, name='update_order_status'),


     path('user_list/', views.user_list, name='user_list'),
     path('block_unblock_user/<int:user_id>/', views.block_unblock_user, name='block_unblock_user'),

     
    path('add_coupon/', views.add_coupon, name='add_coupon'),
     path('coupon_list/', views.coupon_list, name='coupon_list'),
    path('edit_coupon/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('delete_coupon/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),


    path('category_offer/', views.category_offer, name='category_offer'),
    path('edit_offer/<int:offer_id>/', views.edit_offer, name='edit_offer'),
    path('delete_offer/<int:offer_id>/', views.delete_offer, name='delete_offer'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('chart/',views.charts,name='charts'),
    path('reports/',views.reports,name='reports'),
    path('sales-report/', views.sales_report, name='sales_report'),

    path('filtered_sales/', views.filtered_sales, name='filtered_sales'),
]

fkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get-names/',get_names),
    path('',include('user.urls')),
    path('account/',include('account.urls')),
    path('category/',include('category.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('payment/',include('payment.urls')),
    path('wallet_coupon/',include('wallet_coupon.urls')),

]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path,include
from . import views

app_name = 'product'

urlpatterns = [

    path('product-list/', views.product_list, name='product-list'),
    path('add-product/', views.add_product, name='add-product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('soft_delete_product/<int:product_id>/', views.soft_delete_product, name='soft_delete_product'),
    
    path('variant',views.variant_list,name='variant-list'),
    path('add-variant',views.add_variant,name='add-variant'),
    path('add-variant/<int:variant_id>/', views.add_variant, name='edit-variant'),
    path('delete-variant/<int:variant_id>/', views.delete_variant, name='delete-variant'),
]

product/models.py
from django.db import models

# Create your models here.

category/forms.py
from django import forms
from .models import ProductImage


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

product/forms.py
from django import forms
from category.models import Product,ProductVariant,COLOR_CHOICES,SIZE_CHOICES

class AddProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = [ 'product_name', 'category', 'brand', 'description', 'price', 'image']


class AddVariantForm(forms.ModelForm):
    color = forms.ChoiceField(choices=COLOR_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))
    size = forms.ChoiceField(choices=SIZE_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model=ProductVariant
        fields=['product','color','size','stock','is_active']

category/views.py
from django.shortcuts import render,redirect
from .models import *
from account.models import *
from user.models import *
from wallet_coupon.models import *
from django.contrib.auth.decorators import login_required 
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.cache import cache_control
from django.http import HttpResponseBadRequest
from django.contrib import messages
from django.utils import timezone
from django.db.models import Sum, F, Value, Count
from datetime import datetime, timedelta
from collections import defaultdict
# Create your views here.


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def brand_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    search_query = request.GET.get('search')

    if search_query:
        brands = Brand.objects.filter(Q(brand_name__icontains=search_query))
    else:
        brands = Brand.objects.all()

    return render(request, 'admin_side/brand.html', {'brands': brands})



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_brand(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method=='POST':
        brand_name=request.POST['brand_name']
        brands=Brand(brand_name=brand_name)
        brands.save()   
        return redirect('category:brand-list')    
    return render(request, 'admin_side/add_brand.html')



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_brand(request,brand_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    brands = get_object_or_404(Brand, brand_name=brand_name)
    if request.method=='POST':
        brand_name = request.POST.get('brand_name')
        brands.brand_name = brand_name
        brands.save()
        return redirect('category:brand-list')

    else:
        context = {
            'brands':brands
        }

    return render(request, 'admin_side/edit_brand.html', context)    



@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_brand(request, brand_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    brands = get_object_or_404(Brand, brand_name=brand_name)
    if request.method == 'POST':
        brands.delete()
        return redirect('category:brand-list')
    return redirect('category:brand-list')



# ---------------------------- category----------------------------


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def category_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    search_query = request.GET.get('search')

    if search_query:
        categories = Category.objects.filter(Q(category_name__icontains=search_query))
    else:
        categories = Category.objects.all()

    context={
        'categories':categories
    } 

    return render(request,'admin_side/category.html',context)     


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_category(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method == 'POST':
        category_name = request.POST.get('category_name')

        category = Category(category_name=category_name)
        category.save()
        
        return redirect('category:category-list')
    
    return render(request, 'admin_side/add_category.html')


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_category(request,category_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    category=get_object_or_404(Category, category_name=category_name)
    if request.method=='POST':
        category_name=request.POST['category_name']
        category.category_name = category_name
        category.save()

        return redirect('category:category-list')
    else:
        context = {
            'category':category
        }
    
    return render(request, 'admin_side/edit_category.html', context)


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_category(request, category_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    category = get_object_or_404(Category, category_name=category_name)
    if request.method == 'POST':
        category.delete()
        return redirect('category:category-list')
    # return render(request, 'admin_side/category_list.html', {'category': category})
    return redirect('category:category-list')




#------------------------------------------------------user listing-----------------------------------------------------------------

@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def user_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    search_query = request.GET.get('search', '')

    # Query the users based on the search query
    if search_query:
        users = Account.objects.filter(name__icontains=search_query)
    else:
        users = Account.objects.all()

    context = {
        'users': users
    }

    return render(request, 'admin_side/user_list.html', context)


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def block_unblock_user(request, user_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    user = get_object_or_404(Account, id=user_id)

    # Toggle the is_blocked status of the user
    if user.is_active:
        user.is_active=False
        if request.user == user:
            logout(request)

    else:
        user.is_active=True
        
    user.save()
        

    return redirect('category:user_list')



#-------------------------------------------------------order-listing----------------------------------------------------------------------------
@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def order_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    orders = Order.objects.all().order_by('-created_at')  # Fetch all orders from the Order model
    context = {'orders': orders}
    return render(request, 'admin_side/order_list.html', context)



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def ordered_product_details(request, order_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    order = Order.objects.get(id=order_id)
    ordered_products = OrderProduct.objects.filter(order=order)
    for i in ordered_products:
        total=+i.product_price

    context = {
        'order': order,
        'ordered_products': ordered_products,
    }
    return render(request, 'admin_side/ordered_product_details.html', context)



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update_order_status(request, order_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method == 'POST':
        order = get_object_or_404(Order, id=int(order_id))
        status = request.POST['status']
        order.status = status
        order.save()
        return redirect('category:order_list')
    else:
        return HttpResponseBadRequest("Bad request.")
    


# -----------------------------------------------------------coupon---------------------------------------------------------



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def coupon_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    coupons = Coupon.objects.all()
    context = {
        'coupons': coupons
    }
    return render(request, 'admin_side/coupon_list.html', context)



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_coupon(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method == 'POST':
        coupon_code = request.POST.get('coupon_code')
        discount_amount = request.POST.get('discount_amount')
        minimum_amount = request.POST.get('minimum_amount')
        valid_from = request.POST.get('valid_from')
        valid_to = request.POST.get('valid_to')

        coupon = Coupon(
            coupon_code=coupon_code,
            discount_amount=discount_amount,
            minimum_amount=minimum_amount,
            valid_from=valid_from,
            valid_to=valid_to
        )
        coupon.save()

        return redirect('category:coupon_list')

    return render(request, 'admin_side/add_coupon.html')



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_coupon(request, coupon_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    try:
        # Get the coupon instance by its ID

templates/admin_side/add_brand.html
{% extends 'admin_side/base.html' %}
{% load static %}


{% block title %}Brands{% endblock title %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Add Brand</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" action="{% url 'category:add_brand' %}">
                        {% csrf_token %}
                        <div class="d-flex flex-column align-items-center"> <!-- Center the form -->
                            <div class="mb-3">
                                <label for="{{ form.name.id_for_label }}">Brand Name</label>
                                <input type="text" class="form-control" id="brand_name" name="brand_name" >
                            </div>

                            <div class="mb-3">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="{% url 'category:brand-list' %}" class="btn btn-secondary ms-2">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_side/add_variant.html
{% extends 'admin_side/base.html' %}
{% load static %}

{% block title %}Add variant{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title" style="margin-top: 70px;">
                        {% if variant_id %}
                            Edit Variant
                        {% else %}
                            Add Variant
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" action="{% if variant_id %}{% url 'product:edit-variant' variant_id %}{% else %}{% url 'product:add-variant' %}{% endif %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="product">Product</label>
                            {{ form.product }}
                        </div>

                        <div class="row mb-3">
                            <div class="col-sm-6">
                                <label for="{{ form.size.id_for_label }}">Size</label>
                                {{ form.size }}
                            </div>
                            <div class="col-sm-6">
                                <label for="{{ form.color.id_for_label }}">Color</label>
                                {{ form.color }}
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="{{ form.stock.id_for_label }}">Stock</label>
                            {{ form.stock }}
                            <label for="{{ form.is_active.id_for_label }}">Is Active</label>
                            {{ form.is_active }}
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">
                                {% if variant_id %}Update{% else %}Add{% endif %}
                            </button>
                            <a href="{% url 'product:variant-list' %}" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Function to initialize the Cropper.js instance for image cropping
    function initImageCropper() {
        const imageInput = document.getElementById('id_images');
        const imagePreview = document.getElementById('image-preview');
        const cropButton = document.getElementById('crop-button');
      
        imageInput.addEventListener('change', function (e) {
          const file = e.target.files[0];
      
          if (!file) return;
      
          const reader = new FileReader();
      
          reader.onload = function () {
            const img = new Image();
            img.src = reader.result;
      
            img.onload = function () {
              // Clear previous previews and append the new one
              imagePreview.innerHTML = '';
              imagePreview.appendChild(img);
      
              // Initialize Cropper.js
              const cropper = new Cropper(img, {
                aspectRatio: 1, // Set the aspect ratio for cropping
                viewMode: 1,
                guides: true,
                background: false,
                autoCropArea: 0.8,
                responsive: true,
              });
      
              // Show the crop button after image loaded
              cropButton.style.display = 'block';
      
              // Attach event listener to crop button
              cropButton.addEventListener('click', function () {
                // Get cropped canvas and convert it to blob
                const croppedCanvas = cropper.getCroppedCanvas();
                croppedCanvas.toBlob(function (blob) {
                  // Create a new image element to preview the cropped image
                  const croppedImg = new Image();
                  croppedImg.src = URL.createObjectURL(blob);
      
                  // Set the size of the preview image
                  croppedImg.style.width = '840px';
                  croppedImg.style.height = '840px';
      
                  // Clear previous previews and append the new one
                  imagePreview.innerHTML = '';
                  imagePreview.appendChild(croppedImg);

                  // Update the hidden field with the cropped image data
                  const croppedImageInput = document.getElementById('cropped-image');
                  croppedImageInput.value = blob;
                });
              });
            };
          };
      
          reader.readAsDataURL(file);
        });
      }
      
      // Call the function to initialize the image cropper
      initImageCropper();
</script>

{% endblock %}

templates/admin_side/brand.html
{% extends 'admin_side/base.html' %}
{% load static %}


{% block title %}Brands{% endblock title %}


{% block content %}
<div class="col-lg-12 d-flex align-items-stretch">
    <div class="card w-100">
        <div class="card-body p-4">
            <h5 class="card-title fw-semibold mb-4">Brand List</h5>
            <div class="search-container">
                <form action="{% url 'category:brand-list' %}" method="get">
                    <input type="text" name="search" placeholder="Search by brand name">
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
            <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'category:add_brand' %}" class="btn btn-primary">Add Brand</a>
            </div>
            <div class="table-responsive">
                <table class="table text-nowrap mb-0 align-middle">
                    <thead class="text-dark fs-4">
                        <tr>
                            <th class="border-bottom-0">
                                <h6 class="fw-semibold mb-0">Brand Name</h6>
                            </th>
                            <th class="border-bottom-0">
                                <h6 class="fw-semibold mb-0">Actions</h6>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for brand in brands %}
                        <tr>
                            <td>{{ brand.brand_name }}</td>
                            <td>
                                <a href="{% url 'category:edit_brand' brand.brand_name %}" class="btn btn-sm btn-primary">Edit</a>
                                <form method="post" action="{% url 'category:delete_brand' brand.brand_name %}" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this category?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_side/category.html
{% extends 'admin_side/base.html' %}
{% load static %}


{% block title %}Category{% endblock title %}

{% block content %}
<div class="col-lg-12 d-flex align-items-stretch">
    <div class="card w-100">
        <div class="card-body p-4">
            <h5 class="card-title fw-semibold mb-4">Category List</h5>
            <div class="search-container">
                <form action="{% url 'category:category-list' %}" method="get">
                    <input type="text" name="search" placeholder="Search by category name">
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>
            <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'category:add-category' %}" class="btn btn-primary">Add Category</a>
            </div>
            <div class="table-responsive">
                <table class="table text-nowrap mb-0 align-middle">
                    <thead class="text-dark fs-4">
                        <tr>
                            <th class="border-bottom-0">
                                <h6 class="fw-semibold mb-0">Category Name</h6>
                            </th>
                            <th class="border-bottom-0">
                                <h6 class="fw-semibold mb-0">Actions</h6>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <td>{{ category.category_name }}</td>
                            <td>
                                <a href="{% url 'category:edit-category' category.category_name %}" class="btn btn-sm btn-primary">Edit</a>
                                <form method="post" action="{% url 'category:delete-category' category.category_name %}" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this category?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/admin_side/order_list.html
{% extends 'admin_side/base.html' %}
{% load static %}


{% block title %}Order List{% endblock title %}


{% block content %}
<div class="container">
    <h1>Order History</h1>
    <div class="table-responsive">
        <form method="post">
            {% csrf_token %}
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>Order ID</th>
                        <th>Ordered products</th>
                        <th>Order Total</th>
                        
                        <!-- Add other order-related columns as needed -->
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.order_number }}</td>
                        <td><a href="{% url 'category:ordered_product_details' order_id=order.id %}">View Details</a></td>
                        <td>${{ order.order_total }}</td>
                        <!-- Add other order-related data as needed -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    </div>
</div>






{% endblock %}

templates/admin_side/products.html
{% extends 'admin_side/base.html' %}
{% load static %}



{% block title %}Products hj{% endblock title %}

{% block content %}
<style>
  /* Custom CSS to reduce table size and center it */
  .table-container {
    max-width: 1000px; /* Set the maximum width of the table */
    margin: 100px auto; /* Center the table horizontally and add margin at the top */
  }

  .search-container {
    display: flex;
    justify-content: space-between;
    margin-bottom: 20px; /* Add some space between the search bar and the button */
  }

  /* Add padding to the table cells */
  .table th,
  .table td {
    padding: 8px;
  }

  /* Center the text in the "Actions" column */
  .table td.actions {
    text-align: center;
  }
</style>

<div class="col-lg-12 d-flex align-items-stretch">
  <div class="card w-100">
    <div class="card-body p-4">
      <h5 class="card-title fw-semibold mb-4">Product List</h5>
      <div class="search-container">
        <!-- Search bar -->
        <form action="{% url 'product:product-list' %}" method="get">
          <input type="text" name="search" placeholder="Search by product name">
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
        <!-- Add Product button -->
        <a href="{% url 'product:add-product' %}" class="btn btn-primary">Add Product</a>
      </div>

      <div class="table-responsive">
        <table class="table text-nowrap mb-0 align-middle">
            <thead class="text-dark fs-4">
                <tr>
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Product Id</h6>
                    </th>
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Name</h6>
                    </th>
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Category</h6>
                    </th>
                    <!-- <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Description</h6>
                    </th> -->
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Price</h6>
                    </th>
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Brand</h6>
                    </th>
                    
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Image</h6>
                    </th>
                    <th class="border-bottom-0">
                        <h6 class="fw-semibold mb-0">Actions</h6>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ product.product_id }}</td>
                    <td>{{ product.product_name }}</td>
                    <td>{{ product.category.category_name }}</td> {# Use product.category.category_name to access the category name #}
                    <!-- <td>{{ product.description }}</td> -->
                    <td>{{ product.price }}</td>
                    <td>{{ product.brand.brand_name  }}</td>
                  
                    <td><img src="{{ product.image.url}}" alt="{{ product.name }}" height="50"></td>
                    <td class="actions">
                        <a href="{% url 'product:edit_product' product.product_id %}" class="btn btn-sm btn-primary">Edit</a>
                        <form method="post" action="{% url 'product:soft_delete_product' product.product_id %}" style="display: inline;">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this product?')">Delete</button>
                      </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    </div>
  </div>
</div>
{% endblock %}