account/urls.py
from django.urls import path,include
from . import views

app_name = 'account'

urlpatterns = [
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/dashboard/', views.admin_dashboard, name="admin_dashboard"),
    path('admin/logout/',views.admin_logout,name='admin_logout'),
    
    path('index',views.index,name='index'),
    path('user-login/',views.user_login,name='user-login'),
    path('user-signup/',views.user_signup,name='user-signup'),
    path('user-logout',views.user_logout,name='user-logout'),
    path('sent-otp',views.sent_otp,name='sent-otp'),
    path('verify-otp',views.verify_otp,name='verify-otp'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('verify-otp/forgot_password',views.verify_otp_forgot_password,name='verify-otp-forgot-password'),
    path('sent-otp/forgot_password',views.sent_otp_forgot_password,name='sent-otp-forgot-password'),
    path('resend',views.resend_otp,name='resend-otp'),
   
]

cart/urls.py
from django.urls import path,include
from . import views

app_name = 'cart'

urlpatterns = [

    path('shoping_cart/', views.cart, name='shopping_cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('add_quantity_to_cart/<int:product_id>/<int:cart_item_id>/', views.add_quantity_to_cart, name='add_quantity_to_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    

    path('ajax/update/cart/', views.newcart_update, name='newcart_update'),
    path('ajax/remove/cart/', views.remove_cart_item_fully, name='remove_cart_item_fully'),


    path('add_from_wishlist/<int:product_id>',views.add_item_from_wishlist,name='add_from_wishlist')

   
]

category/urls.py
from django.urls import path,include
from . import views

app_name = 'category'

urlpatterns = [
    
    path('brand-list/', views.brand_list, name='brand-list'),
    path('add-brand/', views.add_brand, name='add_brand'),
    path('edit-brand/<str:brand_name>', views.edit_brand, name='edit_brand'),
    path('delete-brand/<str:brand_name>', views.delete_brand, name='delete_brand'),


    path('category-list/', views.category_list, name='category-list'),
    path('add-category/', views.add_category, name='add-category'),
    path('edit-category/<str:category_name>/', views.edit_category, name='edit-category'),
    path('delete-category/<str:category_name>/', views.delete_category, name='delete-category'),

    path('order_list/', views.order_list, name='order_list'),
    path('ordered_product_details/<int:order_id>', views.ordered_product_details, name='ordered_product_details'),
    path('update_order_status/<str:order_id>/', views.update_order_status, name='update_order_status'),


     path('user_list/', views.user_list, name='user_list'),
     path('block_unblock_user/<int:user_id>/', views.block_unblock_user, name='block_unblock_user'),

     
    path('add_coupon/', views.add_coupon, name='add_coupon'),
     path('coupon_list/', views.coupon_list, name='coupon_list'),
    path('edit_coupon/<int:coupon_id>/', views.edit_coupon, name='edit_coupon'),
    path('delete_coupon/<int:coupon_id>/', views.delete_coupon, name='delete_coupon'),


    path('category_offer/', views.category_offer, name='category_offer'),
    path('edit_offer/<int:offer_id>/', views.edit_offer, name='edit_offer'),
    path('delete_offer/<int:offer_id>/', views.delete_offer, name='delete_offer'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('chart/',views.charts,name='charts'),
    path('reports/',views.reports,name='reports'),
    path('sales-report/', views.sales_report, name='sales_report'),

    path('filtered_sales/', views.filtered_sales, name='filtered_sales'),
]

fkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from user.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get-names/',get_names),
    path('',include('user.urls')),
    path('account/',include('account.urls')),
    path('category/',include('category.urls')),
    path('product/',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('payment/',include('payment.urls')),
    path('wallet_coupon/',include('wallet_coupon.urls')),

]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path,include
from . import views

app_name = 'payment'

urlpatterns = [

    path('payments/', views.payments, name='payments'),
    
]

category/forms.py
from django import forms
from .models import ProductImage


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

category/views.py
from django.shortcuts import render,redirect
from .models import *
from account.models import *
from user.models import *
from wallet_coupon.models import *
from django.contrib.auth.decorators import login_required 
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from django.views.decorators.cache import cache_control
from django.http import HttpResponseBadRequest
from django.contrib import messages
from django.utils import timezone
from django.db.models import Sum, F, Value, Count
from datetime import datetime, timedelta
from collections import defaultdict
# Create your views here.


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def brand_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    search_query = request.GET.get('search')

    if search_query:
        brands = Brand.objects.filter(Q(brand_name__icontains=search_query))
    else:
        brands = Brand.objects.all()

    return render(request, 'admin_side/brand.html', {'brands': brands})



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_brand(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method=='POST':
        brand_name=request.POST['brand_name']
        brands=Brand(brand_name=brand_name)
        brands.save()   
        return redirect('category:brand-list')    
    return render(request, 'admin_side/add_brand.html')



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_brand(request,brand_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    brands = get_object_or_404(Brand, brand_name=brand_name)
    if request.method=='POST':
        brand_name = request.POST.get('brand_name')
        brands.brand_name = brand_name
        brands.save()
        return redirect('category:brand-list')

    else:
        context = {
            'brands':brands
        }

    return render(request, 'admin_side/edit_brand.html', context)    



@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_brand(request, brand_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    brands = get_object_or_404(Brand, brand_name=brand_name)
    if request.method == 'POST':
        brands.delete()
        return redirect('category:brand-list')
    return redirect('category:brand-list')



# ---------------------------- category----------------------------


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def category_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    search_query = request.GET.get('search')

    if search_query:
        categories = Category.objects.filter(Q(category_name__icontains=search_query))
    else:
        categories = Category.objects.all()

    context={
        'categories':categories
    } 

    return render(request,'admin_side/category.html',context)     


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_category(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method == 'POST':
        category_name = request.POST.get('category_name')

        category = Category(category_name=category_name)
        category.save()
        
        return redirect('category:category-list')
    
    return render(request, 'admin_side/add_category.html')


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_category(request,category_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    category=get_object_or_404(Category, category_name=category_name)
    if request.method=='POST':
        category_name=request.POST['category_name']
        category.category_name = category_name
        category.save()

        return redirect('category:category-list')
    else:
        context = {
            'category':category
        }
    
    return render(request, 'admin_side/edit_category.html', context)


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delete_category(request, category_name):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    category = get_object_or_404(Category, category_name=category_name)
    if request.method == 'POST':
        category.delete()
        return redirect('category:category-list')
    # return render(request, 'admin_side/category_list.html', {'category': category})
    return redirect('category:category-list')




#------------------------------------------------------user listing-----------------------------------------------------------------

@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def user_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    search_query = request.GET.get('search', '')

    # Query the users based on the search query
    if search_query:
        users = Account.objects.filter(name__icontains=search_query)
    else:
        users = Account.objects.all()

    context = {
        'users': users
    }

    return render(request, 'admin_side/user_list.html', context)


@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def block_unblock_user(request, user_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    user = get_object_or_404(Account, id=user_id)

    # Toggle the is_blocked status of the user
    if user.is_active:
        user.is_active=False
        if request.user == user:
            logout(request)

    else:
        user.is_active=True
        
    user.save()
        

    return redirect('category:user_list')



#-------------------------------------------------------order-listing----------------------------------------------------------------------------
@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def order_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    orders = Order.objects.all().order_by('-created_at')  # Fetch all orders from the Order model
    context = {'orders': orders}
    return render(request, 'admin_side/order_list.html', context)



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def ordered_product_details(request, order_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    order = Order.objects.get(id=order_id)
    ordered_products = OrderProduct.objects.filter(order=order)
    for i in ordered_products:
        total=+i.product_price

    context = {
        'order': order,
        'ordered_products': ordered_products,
    }
    return render(request, 'admin_side/ordered_product_details.html', context)



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def update_order_status(request, order_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method == 'POST':
        order = get_object_or_404(Order, id=int(order_id))
        status = request.POST['status']
        order.status = status
        order.save()
        return redirect('category:order_list')
    else:
        return HttpResponseBadRequest("Bad request.")
    


# -----------------------------------------------------------coupon---------------------------------------------------------



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def coupon_list(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    coupons = Coupon.objects.all()
    context = {
        'coupons': coupons
    }
    return render(request, 'admin_side/coupon_list.html', context)



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def add_coupon(request):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    if request.method == 'POST':
        coupon_code = request.POST.get('coupon_code')
        discount_amount = request.POST.get('discount_amount')
        minimum_amount = request.POST.get('minimum_amount')
        valid_from = request.POST.get('valid_from')
        valid_to = request.POST.get('valid_to')

        coupon = Coupon(
            coupon_code=coupon_code,
            discount_amount=discount_amount,
            minimum_amount=minimum_amount,
            valid_from=valid_from,
            valid_to=valid_to
        )
        coupon.save()

        return redirect('category:coupon_list')

    return render(request, 'admin_side/add_coupon.html')



@login_required(login_url='account:admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_coupon(request, coupon_id):
    if not request.user.is_authenticated:
        return redirect('account:admin_login')
    
    try:
        # Get the coupon instance by its ID

templates/user_side/extend.html
{% extends 'user_side/base.html' %}


{% block content %}


<h1>hellow</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
    
{% endblock  %}

templates/user_side/forgot_password.html
<!-- templates/user_side/forgot_password.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Forgot Password</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            margin-top: 100px;
        }
        .card {
            border: none;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            border-radius: 10px;
            padding: 30px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <h1 class="text-center mb-4">Forgot Password</h1>
                    <form method="post" class="mb-4" action="{% url 'account:forgot_password' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="password">enter your email:</label>
                            <input type="email" name="email" class="form-control" required>
                            <label for="password">enter your password:</label>
                            <input type="password" name="password" class="form-control" required>
                            <label for="password">re-enter your password:</label>
                            <input type="password" name="re_password" class="form-control" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Send OTP</button>
                    </form>
                    <div class="text-center">
                        <a href="{% url 'account:user-login' %}" class="btn btn-link">Back to Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Include Bootstrap JS (Optional) -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- altertify -->

	<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
	<script>
		alertify.set('notifier','position', 'top-center');
		{% for msg in messages %}
	
			alertify.success('{{msg}}');
		{%endfor%}
		 
	</script>
</body>
</html>

templates/user_side/order_received_email.html
{% autoescape off %}

Hi {{ user.first_name }},


YOUR ORDER HAS RECEIVED

Order Number: {{ order.order_number }}

{% endautoescape %}

templates/user_side/verify_otp.html
<!DOCTYPE html>
<html>
<head>
    <title>OTP Verification</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- alterify -->

<!-- CSS -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
<!-- Default theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
<style>
    .red-text {
        color: red;
    }
</style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="mt-5 mb-4">OTP Verification</h1>
                <form method="post" class="mb-5">
                    {% csrf_token %}
                    <p>Enter the OTP sent to your email:</p>
                    <div class="form-group">
                        <label for="otp">OTP:</label>
                        <input type="text" name="otp" class="form-control" required>
                        <p id="timer">Time remaining: <span id="countdown">60</span> seconds</p>
                    </div>
                    <button type="submit" class="btn btn-primary">Verify OTP</button>
                </form>
                
                <a id="resend-link" style="display: none;" href="{% url 'account:resend-otp' %}">Resend OTP</a>
            </div>
        </div>
    </div>

    <script>
        function startTimer(duration, display) {
            var timer = duration, seconds;
    
            var countdown = setInterval(function () {
                seconds = parseInt(timer % 60, 10);
    
                seconds = seconds < 10 ? "0" + seconds : seconds;
    
                var timeText = "00:" + seconds;
                display.textContent = timeText;
    
                if (timer < 10) {
                    display.classList.add("red-text");
                }
    
                if (--timer < 0) {
                    clearInterval(countdown);
                    // Handle timer expiration here (e.g., show Resend OTP link)
                    document.getElementById("resend-link").style.display = "block";
                }
            }, 1000);
        }
    
        window.onload = function () {
            var thirtySeconds = 60;
            var display = document.querySelector('#timer');
            startTimer(thirtySeconds, display);
        };
    </script>
    
    

    <!-- Include Bootstrap JS (Optional) -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- altertify -->

	<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
	<script>
		alertify.set('notifier','position', 'top-center');
		{% for msg in messages %}
	
			alertify.success('{{msg}}');
		{%endfor%}
		 
	</script>
</body>
</html>